CREATE DATABASE IF NOT EXISTS `postal` DEFAULT CHARACTER SET UTF8;

USE `postal`;

CREATE TABLE if NOT EXISTS `worldwide`(
`Id` INT(11) NOT NULL AUTO_INCREMENT,
`countryCode` CHAR(2) DEFAULT NULL ,
`postalCode` VARCHAR(20) DEFAULT NULL ,
`placeName` VARCHAR(180) DEFAULT NULL ,
`stateName` VARCHAR(100) DEFAULT NULL ,
`stateCode` VARCHAR(20) DEFAULT NULL ,
`CountyName` VARCHAR(100) DEFAULT NULL ,
`CountyCode` VARCHAR(20) DEFAULT NULL ,
`CommunityName` VARCHAR(100) DEFAULT NULL ,
`CommunityCode` VARCHAR(20) DEFAULT NULL ,
`lat` DOUBLE DEFAULT NULL ,
`lon` DOUBLE DEFAULT NULL ,
`accuracy` INT(11) NOT NULL DEFAULT 0 ,
PRIMARY KEY (`Id`),
KEY `KEY_PostalCode` (`postalCode`)
) ENGINE = INNODB	DEFAULT CHARSET = UTF8
;

CREATE TABLE if NOT EXISTS `countrycode`(
`Code` CHAR(2) NOT NULL,
`Name` VARCHAR(255) DEFAULT NULL,
PRIMARY KEY (`Code`)
) ENGINE=INNODB DEFAULT CHARSET=UTF8 
;
